config/routes.rb
Rails.application.routes.draw do
  
  root 'images#index'

  get 'upload' => 'images#new', as: 'upload'

  resources :images
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :images
	validates :name, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :get_category_nav
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def get_category_nav
  	@category_nav = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'New category created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category Updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:notice] = 'Category Deleted'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<br>
	<%= f.submit class: 'btn btn-primary' %>
	<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |cat| %>
		<tr>
			<td><%= link_to cat.name, category_path(cat) %></td>
			<td>
				<%= link_to 'Show', category_path(cat), class: 'btn btn-xs btn-default' %>
				<%= link_to 'Edit', edit_category_path(cat), class: 'btn btn-xs btn-primary' %>
				<%= link_to 'Delete', category_path(cat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add Category', new_category_path, class: 'btn btn-primary' %>

app/views/categories/new.html.erb
<h1>Add new Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>
<% if @category.images.any? %>
	<% @category.images.each do |img| %>
		<%= img %>
	<% end %>
<% else %>
	<p>This category has no images yet.</p>
<% end %>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<h1>Images#index</h1>
<p>Find me in app/views/images/index.html.erb</p>

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/new.html.erb</p>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top hidden">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Gallery</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', root_path %></li>
          <li><%= link_to 'Contact', root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          	<ul class="dropdown-menu">
		          <% @category_nav.each do |cat| %>
		          	<li><%= link_to cat.name, cat %></li>
		          <% end %>
          	</ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        	<li><%= link_to 'Upload Photo', upload_path %></li>
        	<li><%= link_to 'Add Category', new_category_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
	</nav>
	<section>
		<div class="container">
			<% if flash[:notice] %>
				<div class="alert alert-success"><%= flash[:notice] %></div>
			<% end %>
			<% if flash[:alert] %>
				<div class="alert alert-danger"><%= flash[:alert] %></div>
			<% end %>
			<%= yield %>
		</div>
	</section>
	<footer class="footer">
    <div class="container">
      <p class="text-muted">Place sticky footer content here.</p>
    </div>
  </footer>
</body>
</html>